import React, { createContext, useContext, useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';

interface Language {
  [key: string]: string;
}

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Language> = {
  az: {
    'nav.home': 'Ana səhifə',
    'nav.services': 'Xidmətlər',
    'nav.faq': 'Suallar',
    'nav.dashboard': 'Hesab',
    'nav.signIn': 'Daxil ol',
    'nav.signOut': 'Çıxış',
    'nav.about': 'Haqqımızda',
    'nav.contact': 'Əlaqə',
    'nav.socialMedia': 'Sosial Media',
    'nav.socialNetworks': 'Sosial Şəbəkələr',
    'hero.title': 'HitLoyal ilə Brendinizi Gücləndirin',
    'hero.subtitle': 'Instagram, TikTok, YouTube və digər sosial media platformalarında hesablarınızı böyütmək üçün ən keyfiyyətli xidmətlər. Organik böyümə və təhlükəsiz yanaşma ilə real nəticələr əldə edin.',
    'hero.viewServices': 'Xidmətləri Gör',
    'stats.completedOrders': 'Tamamlanmış Sifarişlər',
    'stats.happyCustomers': 'Məmnun Müştərilər',
    'stats.customerSatisfaction': 'Müştəri Məmnuniyyəti',
    'stats.support247': 'Dəstək Xidməti',
    'features.whyUs': 'Niyə HitLoyal?',
    'features.subtitle': 'Sosial media xidmətlərimizlə hesablarınızı güclü şəkildə inkişaf etdirin və real nəticələr əldə edin',
    'features.fastQuality': 'Sürətli və Keyfiyyətli',
    'features.fastQualityDesc': 'Real istifadəçilərlə işləyərək sosial media hesablarınızı sürətli və təhlükəsiz şəkildə inkişaf etdiririk.',
    'features.support247': '24/7 Dəstək Xidməti',
    'features.support247Desc': 'Peşəkar müştəri dəstəyi komandamız həftənin 7 günü sizin xidmətinizdədir.',
    'features.securePayment': 'Təhlükəsiz Ödəniş',
    'features.securePaymentDesc': 'Bütün ödənişləriniz SSL şifrələməsi ilə qorunur və müxtəlif ödəniş üsullarını dəstəkləyirik.',
    'features.guarantee': 'Zəmanət və Keyfiyyət',
    'features.guaranteeDesc': 'Bütün xidmətlərimiz 100% zəmanətlidir və keyfiyyət standartlarımıza uyğundur.',
    'guarantees.resultGuarantee': 'Nəticə Zəmanəti',
    'guarantees.satisfactionGuarantee': 'Məmnuniyyət Zəmanəti',
    'guarantees.support247': '24/7 Müştəri Dəstəyi',
    'guarantees.moneyBack': 'Pul Geri Qaytarma',
    'footer.company': 'Şirkət',
    'footer.whyUs': 'Niyə Bizimlə?',
    'footer.secureReliable': 'Təhlükəsiz və Etibarlı',
    'footer.fastService': 'Sürətli Xidmət',
    'footer.support247': '24/7 Dəstək',
    'footer.description': 'Peşəkar reklam və marketinq agentliyi. Biznesinizi rəqəmsal dünyada gücləndirir, brendinizi növbəti səviyyəyə çıxarırıq. Google reklamları, SMM, SEO və digər xidmətlərlə uğurunuzu təmin edirik.',
    'footer.copyright': '© 2024 HitLoyal. Bütün hüquqlar qorunur. Bu sayt rəsmi olaraq Midiya Agency MMC-ə aiddir. VOEN: 6402180791',
    'footer.trustedPlatform': '1,500+ müştərimizin etibar etdiyi platform',
    'order.title': 'Sifarişinizi Verin',
    'order.subtitle': 'Xidmət seçin və məlumatlarınızı daxil edin',
    'order.details': 'Sifariş Təfərrüatları',
    'order.detailsDesc': 'Sifarişinizi vermək üçün aşağıdakı məlumatları doldurun',
    'order.serviceRequired': 'Xidmət seçmək vacibdir',
    'order.servicesLoading': 'Xidmətlər və parametrlər yüklənir...',
    'order.serviceInfo': 'Xidmət Haqqında',
    'order.serviceInfoLoading': 'Məlumat yüklənir...',
    'order.serviceInfoNotAvailable': 'Bu xidmət üçün ətraflı məlumat mövcud deyil',
    'dashboard.title': 'İdarə Paneli',
    'dashboard.welcome': 'Xoş gəlmisiniz',
    'dashboard.orders': 'Sifarişlər',
    'dashboard.balance': 'Balans',
    'dashboard.topUp': 'Balans Artır',
    'dashboard.paymentHistory': 'Ödəniş Tarixçəsi',
    'dashboard.support': 'Dəstək',
    'dashboard.settings': 'Ayarlar',
    'dashboard.noOrders': 'Sifariş tapılmadı',
    'dashboard.noOrdersDesc': 'Bu kateqoriyada sifariş yoxdur',
    'dashboard.allOrders': 'Bütün Sifarişlər',
    'dashboard.allOrdersDesc': 'Bütün sifarişlərinizin siyahısı və vəziyyəti (Real-time yenilənmə aktiv)',
    'dashboard.placeOrder': 'Sifariş Et',
    'dashboard.pending': 'Gözlənir',
    'dashboard.processing': 'İşlənir',
    'dashboard.completed': 'Tamamlandı',
    'dashboard.completedDesc': 'Uğurla tamamlanan sifarişləriniz',
    'dashboard.cancelled': 'Ləğv edildi',
    'dashboard.profile': 'Profil',
    'dashboard.security': 'Təhlükəsizlik',
    'dashboard.overview': 'Ümumi Baxış',
    'dashboard.recent': 'Son',
    'dashboard.view': 'Baxış',
    'dashboard.viewAll': 'Hamısına bax',
    'dashboard.orderHistory': 'Sifariş Tarixçəsi',
    'dashboard.accountBalance': 'Hesab Balansı',
    'dashboard.quickActions': 'Sürətli Əməliyyatlar',
    'dashboard.newOrder': 'Yeni Sifariş',
    'dashboard.statistics': 'Statistikalar',
    'dashboard.totalSpent': 'Ümumi Xərc',
    'dashboard.totalOrders': 'Ümumi Sifarişlər',
    'dashboard.activeOrders': 'Aktiv Sifarişlər',
    'dashboard.errorOrders': 'Xətalı Sifarişlər',
    'dashboard.completedOrders': 'Tamamlanmış Sifarişlər',
    'dashboard.ordersLoadError': 'Sifarişlər yüklənərkən xəta baş verdi',
    'dashboard.dataLoadError': 'Məlumatlar yüklənərkən xəta baş verdi',
    'dashboard.balanceUpdated': 'Balansınız yeniləndi! +${amount} əlavə edildi',
    'dashboard.paymentSuccess': 'Ödəniş uğurla tamamlandı! Balansınız yenilənəcək.',
    'dashboard.paymentError': 'Ödəniş zamanı xəta baş verdi.',
    'dashboard.loginSuccess': 'Uğurla daxil oldunuz!',
    'dashboard.paymentProcessing': 'Ödəniş prosesi başladı. Balansınız avtomatik yenilənəcək.',
    'dashboard.signOutError': 'Çıxış zamanı xəta baş verdi',
    'dashboard.loading': 'Yüklənir...',
    'dashboard.signingOut': 'Çıxılır...',
    'orders.service': 'Xidmət',
    'orders.platform': 'Platform',
    'orders.quantity': 'Miqdar',
    'orders.price': 'Qiymət',
    'orders.status': 'Status',
    'orders.date': 'Tarix',
    'orders.link': 'Link',
    'orders.comment': 'Şərh',
    'orders.pending': 'Gözlənir',
    'orders.processing': 'İşlənir',
    'orders.completed': 'Tamamlandı',
    'orders.error': 'Xəta',
    'orders.refunded': 'Geri qaytarıldı',
    'orders.stopped': 'Dayandırıldı',
    'orders.cancelled': 'Ləğv edildi',
    'orders.externalId': 'Xarici ID',
    'account.title': 'Hesab Ayarları',
    'account.profile': 'Profil',
    'account.security': 'Təhlükəsizlik',
    'account.personalInfo': 'Şəxsi Məlumatlar',
    'account.fullName': 'Ad Soyad',
    'account.email': 'E-mail',
    'account.save': 'Yadda saxla',
    'account.passwordSecurity': 'Şifrə və Təhlükəsizlik',
    'account.newPassword': 'Yeni Şifrə',
    'account.confirmPassword': 'Şifrəni Təsdiqlə',
    'account.updatePassword': 'Şifrəni Yenilə',
    'account.fullNameRequired': 'Ad Soyad sahəsi mütləqdir',
    'account.profileUpdated': 'Profil uğurla yeniləndi',
    'account.profileUpdateError': 'Profil yenilənərkən xəta baş verdi',
    'account.passwordRequired': 'Bütün şifrə sahələri mütləqdir',
    'account.passwordMismatch': 'Yeni şifrələr uyğun gəlmir',
    'account.passwordMinLength': 'Şifrə ən azı 6 simvol olmalıdır',
    'account.passwordUpdated': 'Şifrə uğurla yeniləndi',
    'account.passwordUpdateError': 'Şifrə yenilənərkən xəta baş verdi',
    'balance.topUp': 'Balans Artır',
    'balance.topUpDesc': 'Hesabınıza balans əlavə edin. Minimum məbləğ $1 USD-dir.',
    'balance.quickSelection': 'Sürətli seçim',
    'balance.amount': 'Məbləğ (USD)',
    'balance.enterAmount': 'Məbləği daxil edin',
    'balance.conversionRate': 'Təxmini çevrilmə məzənnəsi',
    'balance.payAmount': 'ödə',
    'balance.topUpDescription': 'Balans artırılması',
    'payment.history': 'Ödəniş Tarixçəsi',
    'payment.historyDesc': 'Son ödənişlərinizin siyahısı və statusu',
    'payment.date': 'Tarix',
    'payment.type': 'Növ',
    'payment.amount': 'Məbləğ',
    'payment.status': 'Status',
    'payment.provider': 'Ödəniş Sistemi',
    'payment.transactionId': 'Tranzaksiya ID',
    'payment.completed': 'Tamamlandı',
    'payment.pending': 'Gözlənir',
    'payment.failed': 'Uğursuz',
    'payment.cancelled': 'Ləğv edildi',
    'payment.balanceTopup': 'Balans Artırma',
    'payment.orderPayment': 'Sifariş Ödənişi',
    'payment.noPayments': 'Hələ ödəniş yoxdur',
    'payment.noPaymentsDesc': 'İlk ödənişinizi etdikdən sonra burada görünəcək',
    'payment.loading': 'Ödəniş tarixçəsi yüklənir...',
    'support.title': 'Dəstək Xidməti',
    'support.description': 'Bizə yazın və kömək alın',
    'support.ticketTitle': 'Dəstək Tələbi',
    'support.subject': 'Mövzu',
    'support.message': 'Mesaj',
    'support.submit': 'Göndər',
    'support.contactInfo': 'Əlaqə Məlumatları',
    'support.email': 'E-mail',
    'support.phone': 'Telefon',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'support.workingHours': 'İş Saatları',
    'support.faq': 'Tez-tez Verilən Suallar',
    'services.popular': 'Populyar Xidmətlər',
    'about.title': 'HitLoyal Haqqında',
    'about.description': 'Biz rəqəmsal marketinq sahəsində aparıcı agentliklərdən biriyik. 2020-ci ildən bəri müştərilərimizə keyfiyyətli sosial media marketinq, reklam və brendinq xidmətləri təqdim edirik.',
    'about.ourMission': 'Bizim Missiyamız',
    'about.missionText': 'Hər bir müştərimizin rəqəmsal dünyada uğur qazanmasına kömək etmək və onların brendlərini gücləndiməkdir. Biz innovativ həllər, şəffaf proseslər və müştəri məmnuniyyətini prioritet olaraq götürürük. Məqsədimiz Azərbaycanda və regionda rəqəmsal marketinq sahəsində liderlik mövqeyini qorumaq və daha da möhkəmləndirməkdir.',
    'about.whyChooseUs': 'Niyə Məhz Bizi Seçməlisiniz?',
    'about.companyInfo': 'Şirkət Haqqında',
    'about.companyDescription': 'HitLoyal, Midiya Agency MMC-nin nəzarəti altında fəaliyyət göstərən rəqəmsal marketinq platformasıdır. Şirkətimiz rəsmi olaraq qeydiyyatdan keçmişdir və VOEN: 6402180791 nömrəsi ilə tanınır.',
    'about.companyServices': 'Biz sosial media platformalarında organic və ödənişli reklam kampaniyaları, SEO optimallaşdırması, kontent marketinqi və brendinq xidmətləri təqdim edirik. Komandamız müasir texnologiyalar və ən son marketinq trendləri ilə işləyir.',
    'about.security': 'Təhlükəsizlik',
    'about.securityDesc': 'Bütün məlumatlarınız və sifarişləriniz tam təhlükəsizlik altındadır.',
    'about.fastService': 'Sürətli Xidmət',
    'about.fastServiceDesc': 'Sifarişləriniz ən qısa müddətdə yerinə yetirilir.',
    'about.professionalTeam': 'Peşəkar Komanda',
    'about.professionalTeamDesc': 'Təcrübəli mütəxəssislərdən ibarət komandamız sizə yardım edir.',
    'about.targeted': 'Məqsədyönlü',
    'about.targetedDesc': 'Hər layihəyə fərdi yanaşma və maksimal nəticə əldə edirik.',
    'about.quality': 'Keyfiyyət',
    'about.qualityDesc': 'Yüksək keyfiyyətli xidmət və müştəri məmnuniyyəti prioritetimizdir.',
    'about.globalReach': 'Global Əhatə',
    'about.globalReachDesc': 'Dünya üzrə müxtəlif platformalarda xidmət göstəririk.',
    'about.happyCustomers': 'Məmnun Müştəri',
    'about.completedOrders': 'Tamamlanmış Sifariş',
    'about.successRate': 'Uğur Nisbəti',
    'about.supportService': 'Dəstək Xidməti',
    'contact.title': 'Bizimlə Əlaqə',
    'contact.description': 'Suallarınız var? Bizə müraciət edin və peşəkar komandamız sizə kömək etsin. 24/7 dəstək xidməti ilə həmişə yanınızdayıq.',
    'contact.info': 'Əlaqə Məlumatları',
    'contact.writeToUs': 'Bizə Yazın',
    'contact.sendMessage': 'Mesajı Göndər',
    'contact.email': 'E-poçt',
    'contact.phone': 'Telefon',
    'contact.address': 'Ünvan',
    'contact.workHours': 'İş Saatları',
    'contact.support247': '24/7 Dəstək',
    'contact.whyHitLoyal': 'Niyə HitLoyal?',
    'contact.fastResponse': 'Sürətli cavab müddəti (24 saat ərzində)',
    'contact.professionalConsult': 'Peşəkar konsultasiya xidməti',
    'contact.personalizedSolutions': 'Fərdiləşdirilmiş həllər',
    'contact.transparentPricing': 'Şəffaf qiymətləndirmə',
    'contact.formDesc': 'Sualınızı göndərin və tezliklə sizinlə əlaqə saxlayaq.',
    'contact.fullName': 'Ad və Soyad',
    'contact.subject': 'Mövzu',
    'contact.message': 'Mesaj',
    'contact.namePlaceholder': 'Adınızı daxil edin',
    'contact.emailPlaceholder': 'email@example.com',
    'contact.subjectPlaceholder': 'Mesajınızın mövzusu',
    'contact.messagePlaceholder': 'Mesajınızı buraya yazın...',
    'contact.findOffice': 'Ofisimizə Yolunuzu Tapın',
    'contact.officeLocation': 'Bakı şəhəri, Cəfər Cabbarlı küçəsi 44, Caspian Plaza binasında yerləşirik. Metro stansiyalarına yaxın və əlçatan yerdəyik.',
    'contact.addressFull': 'Cəfər Cabbarlı 44 (Caspian Plaza)',
    'contact.city': 'Bakı, Azərbaycan',
    'auth.login': 'Giriş',
    'auth.signup': 'Qeydiyyat',
    'auth.loginTitle': 'Hesaba Giriş',
    'auth.loginDesc': 'Email və şifrənizi daxil edərək hesabınıza daxil olun',
    'auth.signupTitle': 'Yeni Hesab',
    'auth.signupDesc': 'Yeni hesab yaratmaq üçün məlumatlarınızı daxil edin',
    'auth.email': 'Email',
    'auth.password': 'Şifrə',
    'auth.fullName': 'Ad Soyad',
    'auth.fullNamePlaceholder': 'Ad Soyad (minimum 3 hərf)',
    'auth.emailPlaceholder': 'example@example.com',
    'auth.loginButton': 'Daxil ol',
    'auth.signupButton': 'Qeydiyyatdan keç',
    'auth.forgotPassword': 'Şifrəmi unutdum',
    'auth.emailAvailable': 'Email ünvanı əlçatandır',
    'auth.emailTaken': 'Bu email ünvanı artıq mövcuddur',
    'auth.emailCheckError': 'E-poçt yoxlanarkən xəta baş verdi',
    'auth.nameRequirement': 'Ad minimum 3 hərf olmalıdır',
    'auth.nameValid': 'Ad tələbləri qarşılanır',
    'auth.formError': 'Form xətası',
    'auth.formErrorMessage': 'Zəhmət olmasa bütün tələbləri yerinə yetirin',
    'auth.signupError': 'Qeydiyyat Xətası',
    'auth.weakPassword': 'Zəif şifrə',
    'auth.weakPasswordMessage': 'Zəhmət olmasa daha güclü şifrə seçin (ən azı 3/5 bal)',
    'auth.generalError': 'Xəta',
    'auth.signupGeneralError': 'Qeydiyyat zamanı xəta baş verdi',
  },
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.services': 'Hizmetler',
    'nav.faq': 'SSS',
    'nav.dashboard': 'Hesap',
    'nav.signIn': 'Giriş Yap',
    'nav.signOut': 'Çıkış',
    'nav.about': 'Hakkımızda',
    'nav.contact': 'İletişim',
    'nav.socialMedia': 'Sosyal Medya',
    'nav.socialNetworks': 'Sosyal Ağlar',
    'hero.title': 'HitLoyal ile Markanızı Güçlendirin',
    'hero.subtitle': 'Instagram, TikTok, YouTube ve diğer sosyal medya platformlarında hesaplarınızı büyütmek için en kaliteli hizmetler. Organik büyüme ve güvenli yaklaşımla gerçek sonuçlar elde edin.',
    'hero.viewServices': 'Hizmetleri Gör',
    'stats.completedOrders': 'Tamamlanan Siparişler',
    'stats.happyCustomers': 'Mutlu Müşteriler',
    'stats.customerSatisfaction': 'Müşteri Memnuniyeti',
    'stats.support247': 'Destek Hizmeti',
    'features.whyUs': 'Neden HitLoyal?',
    'features.subtitle': 'Sosyal medya hizmetlerimizle hesaplarınızı güçlü şekilde geliştirin ve gerçek sonuçlar elde edin',
    'features.fastQuality': 'Hızlı ve Kaliteli',
    'features.fastQualityDesc': 'Gerçek kullanıcılarla çalışarak sosyal medya hesaplarınızı hızlı ve güvenli şekilde geliştiriyoruz.',
    'features.support247': '7/24 Destek Hizmeti',
    'features.support247Desc': 'Profesyonel müşteri destek ekibimiz haftanın 7 günü hizmetinizde.',
    'features.securePayment': 'Güvenli Ödeme',
    'features.securePaymentDesc': 'Tüm ödemeleriniz SSL şifreleme ile korunur ve çeşitli ödeme yöntemlerini destekliyoruz.',
    'features.guarantee': 'Garanti ve Kalite',
    'features.guaranteeDesc': 'Tüm hizmetlerimiz %100 garantilidir ve kalite standartlarımıza uygundur.',
    'guarantees.resultGuarantee': 'Sonuç Garantisi',
    'guarantees.satisfactionGuarantee': 'Memnuniyet Garantisi',
    'guarantees.support247': '7/24 Müşteri Desteği',
    'guarantees.moneyBack': 'Para İade Garantisi',
    'footer.company': 'Şirket',
    'footer.whyUs': 'Neden Bizimle?',
    'footer.secureReliable': 'Güvenli ve Güvenilir',
    'footer.fastService': 'Hızlı Hizmet',
    'footer.support247': '7/24 Destek',
    'footer.description': 'Profesyonel reklam ve pazarlama ajansı. İşinizi dijital dünyada güçlendiriyor, markanızı bir sonraki seviyeye taşıyoruz. Google reklamları, SMM, SEO ve diğer hizmetlerle başarınızı sağlıyoruz.',
    'footer.copyright': '© 2024 HitLoyal. Tüm hakları saklıdır. Bu site resmi olarak Midiya Agency MMC\'ye aittir. VOEN: 6402180791',
    'footer.trustedPlatform': '1,500+ müşterimizin güvendiği platform',
    'order.title': 'Siparişinizi Verin',
    'order.subtitle': 'Hizmet seçin ve bilgilerinizi girin',
    'order.details': 'Sipariş Detayları',
    'order.detailsDesc': 'Siparişinizi vermek için aşağıdaki bilgileri doldurun',
    'order.serviceRequired': 'Hizmet seçmek zorunludur',
    'order.servicesLoading': 'Hizmetler ve parametreler yükleniyor...',
    'order.serviceInfo': 'Hizmet Hakkında',
    'order.serviceInfoLoading': 'Bilgi yükleniyor...',
    'order.serviceInfoNotAvailable': 'Bu hizmet için detaylı bilgi mevcut değil',
    'dashboard.title': 'Kontrol Paneli',
    'dashboard.welcome': 'Hoş geldiniz',
    'dashboard.orders': 'Siparişler',
    'dashboard.balance': 'Bakiye',
    'dashboard.topUp': 'Bakiye Yükle',
    'dashboard.paymentHistory': 'Ödeme Geçmişi',
    'dashboard.support': 'Destek',
    'dashboard.settings': 'Ayarlar',
    'dashboard.noOrders': 'Sipariş bulunamadı',
    'dashboard.noOrdersDesc': 'Bu kategoride sipariş yok',
    'dashboard.allOrders': 'Tüm Siparişler',
    'dashboard.allOrdersDesc': 'Tüm siparişlerinizin listesi ve durumu (Gerçek zamanlı güncelleme aktif)',
    'dashboard.placeOrder': 'Sipariş Ver',
    'dashboard.pending': 'Bekliyor',
    'dashboard.processing': 'İşleniyor',
    'dashboard.completed': 'Tamamlandı',
    'dashboard.completedDesc': 'Başarıyla tamamlanan siparişleriniz',
    'dashboard.cancelled': 'İptal edildi',
    'dashboard.profile': 'Profil',
    'dashboard.security': 'Güvenlik',
    'dashboard.overview': 'Genel Bakış',
    'dashboard.recent': 'Son',
    'dashboard.view': 'Görüntüle',
    'dashboard.viewAll': 'Tümünü gör',
    'dashboard.orderHistory': 'Sipariş Geçmişi',
    'dashboard.accountBalance': 'Hesap Bakiyesi',
    'dashboard.quickActions': 'Hızlı İşlemler',
    'dashboard.newOrder': 'Yeni Sipariş',
    'dashboard.statistics': 'İstatistikler',
    'dashboard.totalSpent': 'Toplam Harcama',
    'dashboard.totalOrders': 'Toplam Siparişler',
    'dashboard.activeOrders': 'Aktif Siparişler',
    'dashboard.errorOrders': 'Hatalı Siparişler',
    'dashboard.completedOrders': 'Tamamlanan Siparişler',
    'dashboard.ordersLoadError': 'Siparişler yüklenirken hata oluştu',
    'dashboard.dataLoadError': 'Veriler yüklenirken hata oluştu',
    'dashboard.balanceUpdated': 'Bakiyeniz güncellendi! +${amount} eklendi',
    'dashboard.paymentSuccess': 'Ödeme başarıyla tamamlandı! Bakiyeniz güncellenecek.',
    'dashboard.paymentError': 'Ödeme sırasında hata oluştu.',
    'dashboard.loginSuccess': 'Başarıyla giriş yaptınız!',
    'dashboard.paymentProcessing': 'Ödeme süreci başladı. Bakiyeniz otomatik güncellenecek.',
    'dashboard.signOutError': 'Çıkış sırasında hata oluştu',
    'dashboard.loading': 'Yükleniyor...',
    'dashboard.signingOut': 'Çıkış yapılıyor...',
    'orders.service': 'Hizmet',
    'orders.platform': 'Platform',
    'orders.quantity': 'Miktar',
    'orders.price': 'Fiyat',
    'orders.status': 'Durum',
    'orders.date': 'Tarih',
    'orders.link': 'Link',
    'orders.comment': 'Yorum',
    'orders.pending': 'Bekliyor',
    'orders.processing': 'İşleniyor',
    'orders.completed': 'Tamamlandı',
    'orders.error': 'Hata',
    'orders.refunded': 'İade edildi',
    'orders.stopped': 'Durduruldu',
    'orders.cancelled': 'İptal edildi',
    'orders.externalId': 'Dış ID',
    'account.title': 'Hesap Ayarları',
    'account.profile': 'Profil',
    'account.security': 'Güvenlik',
    'account.personalInfo': 'Kişisel Bilgiler',
    'account.fullName': 'Ad Soyad',
    'account.email': 'E-posta',
    'account.save': 'Kaydet',
    'account.passwordSecurity': 'Şifre ve Güvenlik',
    'account.newPassword': 'Yeni Şifre',
    'account.confirmPassword': 'Şifreyi Onayla',
    'account.updatePassword': 'Şifreyi Güncelle',
    'account.fullNameRequired': 'Ad Soyad alanı zorunludur',
    'account.profileUpdated': 'Profil başarıyla güncellendi',
    'account.profileUpdateError': 'Profil güncellenirken hata oluştu',
    'account.passwordRequired': 'Tüm şifre alanları zorunludur',
    'account.passwordMismatch': 'Yeni şifreler eşleşmiyor',
    'account.passwordMinLength': 'Şifre en az 6 karakter olmalıdır',
    'account.passwordUpdated': 'Şifre başarıyla güncellendi',
    'account.passwordUpdateError': 'Şifre güncellenirken hata oluştu',
    'balance.topUp': 'Bakiye Yükle',
    'balance.topUpDesc': 'Hesabınıza bakiye ekleyin. Minimum tutar $1 USD\'dir.',
    'balance.quickSelection': 'Hızlı seçim',
    'balance.amount': 'Tutar (USD)',
    'balance.enterAmount': 'Tutarı girin',
    'balance.conversionRate': 'Yaklaşık dönüşüm oranı',
    'balance.payAmount': 'öde',
    'balance.topUpDescription': 'Bakiye yükleme',
    'payment.history': 'Ödeme Geçmişi',
    'payment.historyDesc': 'Son ödemelerinizin listesi ve durumu',
    'payment.date': 'Tarih',
    'payment.type': 'Tür',
    'payment.amount': 'Tutar',
    'payment.status': 'Durum',
    'payment.provider': 'Ödeme Sistemi',
    'payment.transactionId': 'İşlem ID',
    'payment.completed': 'Tamamlandı',
    'payment.pending': 'Bekliyor',
    'payment.failed': 'Başarısız',
    'payment.cancelled': 'İptal edildi',
    'payment.balanceTopup': 'Bakiye Yükleme',
    'payment.orderPayment': 'Sipariş Ödemesi',
    'payment.noPayments': 'Henüz ödeme yok',
    'payment.noPaymentsDesc': 'İlk ödemenizi yaptıktan sonra burada görünecek',
    'payment.loading': 'Ödeme geçmişi yükleniyor...',
    'support.title': 'Destek Hizmeti',
    'support.description': 'Bize yazın ve yardım alın',
    'support.ticketTitle': 'Destek Talebi',
    'support.subject': 'Konu',
    'support.message': 'Mesaj',
    'support.submit': 'Gönder',
    'support.contactInfo': 'İletişim Bilgileri',
    'support.email': 'E-posta',
    'support.phone': 'Telefon',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'support.workingHours': 'Çalışma Saatleri',
    'support.faq': 'Sıkça Sorulan Sorular',
    'services.popular': 'Popüler Hizmetler',
    'about.title': 'HitLoyal Hakkında',
    'about.description': 'Dijital pazarlama alanında önde gelen ajanslardan biriyiz. 2020\'den beri müşterilerimize kaliteli sosyal medya pazarlama, reklam ve branding hizmetleri sunuyoruz.',
    'about.ourMission': 'Misyonumuz',
    'about.missionText': 'Her müşterimizin dijital dünyada başarı kazanmasına yardım etmek ve markalarını güçlendirmektir. İnovatif çözümler, şeffaf süreçler ve müşteri memnuniyetini öncelik olarak alıyoruz. Amacımız Azerbaycan\'da ve bölgede dijital pazarlama alanında liderlik konumunu korumak ve daha da güçlendirmektir.',
    'about.whyChooseUs': 'Neden Bizi Seçmelisiniz?',
    'about.companyInfo': 'Şirket Hakkında',
    'about.companyDescription': 'HitLoyal, Midiya Agency MMC\'nin kontrolü altında faaliyet gösteren dijital pazarlama platformudur. Şirketimiz resmi olarak kayıtlıdır ve VOEN: 6402180791 numarası ile tanınmaktadır.',
    'about.companyServices': 'Sosyal medya platformlarında organik ve ücretli reklam kampaniyaları, SEO optimizasyonu, içerik pazarlama ve branding hizmetleri sunuyoruz. Ekibimiz modern teknolojiler ve en son pazarlama trendleri ile çalışmaktadır.',
    'about.security': 'Güvenlik',
    'about.securityDesc': 'Tüm bilgileriniz ve siparişleriniz tam güvenlik altındadır.',
    'about.fastService': 'Hızlı Hizmet',
    'about.fastServiceDesc': 'Siparişleriniz en kısa sürede yerine getirilir.',
    'about.professionalTeam': 'Profesyonel Ekip',
    'about.professionalTeamDesc': 'Deneyimli uzmanlardan oluşan ekibimiz size yardımcı olur.',
    'about.targeted': 'Hedef Odaklı',
    'about.targetedDesc': 'Her projeye bireysel yaklaşım ve maksimum sonuç elde ediyoruz.',
    'about.quality': 'Kalite',
    'about.qualityDesc': 'Yüksek kaliteli hizmet ve müşteri memnuniyeti önceliğimizdir.',
    'about.globalReach': 'Global Erişim',
    'about.globalReachDesc': 'Dünya çapında çeşitli platformlarda hizmet veriyoruz.',
    'about.happyCustomers': 'Mutlu Müşteri',
    'about.completedOrders': 'Tamamlanan Sipariş',
    'about.successRate': 'Başarı Oranı',
    'about.supportService': 'Destek Hizmeti',
    'contact.title': 'Bizimle İletişime Geçin',
    'contact.description': 'Sorularınız mı var? Bize ulaşın ve profesyonel ekibimiz size yardımcı olsun. 7/24 destek hizmeti ile her zaman yanınızdayız.',
    'contact.info': 'İletişim Bilgileri',
    'contact.writeToUs': 'Bize Yazın',
    'contact.sendMessage': 'Mesajı Gönder',
    'contact.email': 'E-posta',
    'contact.phone': 'Telefon',
    'contact.address': 'Adres',
    'contact.workHours': 'Çalışma Saatleri',
    'contact.support247': '7/24 Destek',
    'contact.whyHitLoyal': 'Neden HitLoyal?',
    'contact.fastResponse': 'Hızlı yanıt süresi (24 saat içinde)',
    'contact.professionalConsult': 'Profesyonel danışmanlık hizmeti',
    'contact.personalizedSolutions': 'Kişiselleştirilmiş çözümler',
    'contact.transparentPricing': 'Şeffaf fiyatlandırma',
    'contact.formDesc': 'Sorunuzu gönderin ve kısa sürede sizinle iletişime geçelim.',
    'contact.fullName': 'İsim ve Soy isim',
    'contact.subject': 'Konu',
    'contact.message': 'Mesaj',
    'contact.namePlaceholder': 'Adınızı girin',
    'contact.emailPlaceholder': 'email@example.com',
    'contact.subjectPlaceholder': 'Mesajınızın konusu',
    'contact.messagePlaceholder': 'Mesajınızı buraya yazın...',
    'contact.findOffice': 'Ofisimizi Bulun',
    'contact.officeLocation': 'Bakü şehri, Cəfər Cabbarlı caddesi 44, Caspian Plaza binasında yer alıyoruz. Metro istasyonlarına yakın ve ulaşılabilir konumdayız.',
    'contact.addressFull': 'Cəfər Cabbarlı 44 (Caspian Plaza)',
    'contact.city': 'Bakü, Azerbaycan',
    'auth.login': 'Giriş',
    'auth.signup': 'Kayıt',
    'auth.loginTitle': 'Hesaba Giriş',
    'auth.loginDesc': 'E-posta ve şifrenizi girerek hesabınıza giriş yapın',
    'auth.signupTitle': 'Yeni Hesap',
    'auth.signupDesc': 'Yeni hesap oluşturmak için bilgilerinizi girin',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.fullName': 'Ad Soyad',
    'auth.fullNamePlaceholder': 'Ad Soyad (minimum 3 harf)',
    'auth.emailPlaceholder': 'example@example.com',
    'auth.loginButton': 'Giriş Yap',
    'auth.signupButton': 'Kayıt Ol',
    'auth.forgotPassword': 'Şifremi unuttum',
    'auth.emailAvailable': 'Bu e-posta adresi kullanılabilir',
    'auth.emailTaken': 'Bu e-posta adresi zaten kullanılıyor',
    'auth.emailCheckError': 'E-posta kontrol edilirken hata oluştu',
    'auth.nameRequirement': 'Ad minimum 3 harf olmalıdır',
    'auth.nameValid': 'Ad gereksinimleri karşılanıyor',
    'auth.formError': 'Form Hatası',
    'auth.formErrorMessage': 'Lütfen tüm gereksinimleri karşılayın',
    'auth.signupError': 'Kayıt Hatası',
    'auth.weakPassword': 'Zayıf Şifre',
    'auth.weakPasswordMessage': 'Lütfen daha güçlü bir şifre seçin (en az 3/5 puan)',
    'auth.generalError': 'Hata',
    'auth.signupGeneralError': 'Kayıt sırasında hata oluştu',
  },
  en: {
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.faq': 'FAQ',
    'nav.dashboard': 'Dashboard',
    'nav.signIn': 'Sign In',
    'nav.signOut': 'Sign Out',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.socialMedia': 'Social Media',
    'nav.socialNetworks': 'Social Networks',
    'hero.title': 'Boost Your Brand with HitLoyal',
    'hero.subtitle': 'Premium services to grow your accounts on Instagram, TikTok, YouTube and other social media platforms. Get real results with organic growth and secure approach.',
    'hero.viewServices': 'View Services',
    'stats.completedOrders': 'Completed Orders',
    'stats.happyCustomers': 'Happy Customers',
    'stats.customerSatisfaction': 'Customer Satisfaction',
    'stats.support247': 'Support Service',
    'features.whyUs': 'Why HitLoyal?',
    'features.subtitle': 'Powerfully develop your social media accounts with our services and get real results',
    'features.fastQuality': 'Fast & Quality',
    'features.fastQualityDesc': 'We develop your social media accounts quickly and safely by working with real users.',
    'features.support247': '24/7 Support Service',
    'features.support247Desc': 'Our professional customer support team is at your service 7 days a week.',
    'features.securePayment': 'Secure Payment',
    'features.securePaymentDesc': 'All your payments are protected with SSL encryption and we support various payment methods.',
    'features.guarantee': 'Guarantee & Quality',
    'features.guaranteeDesc': 'All our services are 100% guaranteed and comply with our quality standards.',
    'guarantees.resultGuarantee': 'Result Guarantee',
    'guarantees.satisfactionGuarantee': 'Satisfaction Guarantee',
    'guarantees.support247': '24/7 Customer Support',
    'guarantees.moneyBack': 'Money Back Guarantee',
    'footer.company': 'Company',
    'footer.whyUs': 'Why Us?',
    'footer.secureReliable': 'Secure & Reliable',
    'footer.fastService': 'Fast Service',
    'footer.support247': '24/7 Support',
    'footer.description': 'Professional advertising and marketing agency. We strengthen your business in the digital world and take your brand to the next level. We ensure your success with Google ads, SMM, SEO and other services.',
    'footer.copyright': '© 2024 HitLoyal. All rights reserved. This site officially belongs to Midiya Agency MMC. VOEN: 6402180791',
    'footer.trustedPlatform': 'Platform trusted by 1,500+ customers',
    'order.title': 'Place Your Order',
    'order.subtitle': 'Select service and enter your details',
    'order.details': 'Order Details',
    'order.detailsDesc': 'Fill in the following information to place your order',
    'order.serviceRequired': 'Service selection is required',
    'order.servicesLoading': 'Loading services and parameters...',
    'order.serviceInfo': 'About Service',
    'order.serviceInfoLoading': 'Loading information...',
    'order.serviceInfoNotAvailable': 'Detailed information is not available for this service',
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.orders': 'Orders',
    'dashboard.balance': 'Balance',
    'dashboard.topUp': 'Top Up',
    'dashboard.paymentHistory': 'Payment History',
    'dashboard.support': 'Support',
    'dashboard.settings': 'Settings',
    'dashboard.noOrders': 'No orders found',
    'dashboard.noOrdersDesc': 'No orders in this category',
    'dashboard.allOrders': 'All Orders',
    'dashboard.allOrdersDesc': 'List of all your orders and their status (Real-time updates active)',
    'dashboard.placeOrder': 'Place Order',
    'dashboard.pending': 'Pending',
    'dashboard.processing': 'Processing',
    'dashboard.completed': 'Completed',
    'dashboard.completedDesc': 'Your successfully completed orders',
    'dashboard.cancelled': 'Cancelled',
    'dashboard.profile': 'Profile',
    'dashboard.security': 'Security',
    'dashboard.overview': 'Overview',
    'dashboard.recent': 'Recent',
    'dashboard.view': 'View',
    'dashboard.viewAll': 'View All',
    'dashboard.orderHistory': 'Order History',
    'dashboard.accountBalance': 'Account Balance',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.newOrder': 'New Order',
    'dashboard.statistics': 'Statistics',
    'dashboard.totalSpent': 'Total Spent',
    'dashboard.totalOrders': 'Total Orders',
    'dashboard.activeOrders': 'Active Orders',
    'dashboard.errorOrders': 'Error Orders',
    'dashboard.completedOrders': 'Completed Orders',
    'dashboard.ordersLoadError': 'Error occurred while loading orders',
    'dashboard.dataLoadError': 'Error occurred while loading data',
    'dashboard.balanceUpdated': 'Your balance has been updated! +${amount} added',
    'dashboard.paymentSuccess': 'Payment completed successfully! Your balance will be updated.',
    'dashboard.paymentError': 'An error occurred during payment.',
    'dashboard.loginSuccess': 'Successfully logged in!',
    'dashboard.paymentProcessing': 'Payment process started. Your balance will be updated automatically.',
    'dashboard.signOutError': 'Error occurred while signing out',
    'dashboard.loading': 'Loading...',
    'dashboard.signingOut': 'Signing out...',
    'orders.service': 'Service',
    'orders.platform': 'Platform',
    'orders.quantity': 'Quantity',
    'orders.price': 'Price',
    'orders.status': 'Status',
    'orders.date': 'Date',
    'orders.link': 'Link',
    'orders.comment': 'Comment',
    'orders.pending': 'Pending',
    'orders.processing': 'Processing',
    'orders.completed': 'Completed',
    'orders.error': 'Error',
    'orders.refunded': 'Refunded',
    'orders.stopped': 'Stopped',
    'orders.cancelled': 'Cancelled',
    'orders.externalId': 'External ID',
    'account.title': 'Account Settings',
    'account.profile': 'Profile',
    'account.security': 'Security',
    'account.personalInfo': 'Personal Information',
    'account.fullName': 'Full Name',
    'account.email': 'Email',
    'account.save': 'Save',
    'account.passwordSecurity': 'Password & Security',
    'account.newPassword': 'New Password',
    'account.confirmPassword': 'Confirm Password',
    'account.updatePassword': 'Update Password',
    'account.fullNameRequired': 'Full name field is required',
    'account.profileUpdated': 'Profile updated successfully',
    'account.profileUpdateError': 'Error occurred while updating profile',
    'account.passwordRequired': 'All password fields are required',
    'account.passwordMismatch': 'New passwords do not match',
    'account.passwordMinLength': 'Password must be at least 6 characters',
    'account.passwordUpdated': 'Password updated successfully',
    'account.passwordUpdateError': 'Error occurred while updating password',
    'balance.topUp': 'Top Up Balance',
    'balance.topUpDesc': 'Add balance to your account. Minimum amount is $1 USD.',
    'balance.quickSelection': 'Quick selection',
    'balance.amount': 'Amount (USD)',
    'balance.enterAmount': 'Enter amount',
    'balance.conversionRate': 'Approximate conversion rate',
    'balance.payAmount': 'pay',
    'balance.topUpDescription': 'Balance top-up',
    'payment.history': 'Payment History',
    'payment.historyDesc': 'List of your recent payments and their status',
    'payment.date': 'Date',
    'payment.type': 'Type',
    'payment.amount': 'Amount',
    'payment.status': 'Status',
    'payment.provider': 'Payment Provider',
    'payment.transactionId': 'Transaction ID',
    'payment.completed': 'Completed',
    'payment.pending': 'Pending',
    'payment.failed': 'Failed',
    'payment.cancelled': 'Cancelled',
    'payment.balanceTopup': 'Balance Top-up',
    'payment.orderPayment': 'Order Payment',
    'payment.noPayments': 'No payments yet',
    'payment.noPaymentsDesc': 'Your first payment will appear here',
    'payment.loading': 'Loading payment history...',
    'support.title': 'Support Service',
    'support.description': 'Contact us and get help',
    'support.ticketTitle': 'Support Request',
    'support.subject': 'Subject',
    'support.message': 'Message',
    'support.submit': 'Submit',
    'support.contactInfo': 'Contact Information',
    'support.email': 'Email',
    'support.phone': 'Phone',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'support.workingHours': 'Working Hours',
    'support.faq': 'Frequently Asked Questions',
    'services.popular': 'Popular Services',
    'about.title': 'About HitLoyal',
    'about.description': 'We are one of the leading agencies in the digital marketing field. Since 2020, we have been providing quality social media marketing, advertising and branding services to our customers.',
    'about.ourMission': 'Our Mission',
    'about.missionText': 'To help every customer succeed in the digital world and strengthen their brands. We prioritize innovative solutions, transparent processes and customer satisfaction. Our goal is to maintain and further strengthen our leadership position in the digital marketing field in Azerbaijan and the region.',
    'about.whyChooseUs': 'Why Choose Us?',
    'about.companyInfo': 'About Company',
    'about.companyDescription': 'HitLoyal is a digital marketing platform operating under the control of Midiya Agency MMC. Our company is officially registered and is known with VOEN number: 6402180791.',
    'about.companyServices': 'We provide organic and paid advertising campaigns on social media platforms, SEO optimization, content marketing and branding services. Our team works with modern technologies and the latest marketing trends.',
    'about.security': 'Security',
    'about.securityDesc': 'All your information and orders are under complete security.',
    'about.fastService': 'Fast Service',
    'about.fastServiceDesc': 'Your orders are fulfilled in the shortest time possible.',
    'about.professionalTeam': 'Professional Team',
    'about.professionalTeamDesc': 'Our team of experienced specialists helps you.',
    'about.targeted': 'Targeted',
    'about.targetedDesc': 'Individual approach to each project and maximum results.',
    'about.quality': 'Quality',
    'about.qualityDesc': 'High quality service and customer satisfaction is our priority.',
    'about.globalReach': 'Global Reach',
    'about.globalReachDesc': 'We provide services on various platforms worldwide.',
    'about.happyCustomers': 'Happy Customers',
    'about.completedOrders': 'Completed Orders',
    'about.successRate': 'Success Rate',
    'about.supportService': 'Support Service',
    'contact.title': 'Contact Us',
    'contact.description': 'Have questions? Contact us and let our professional team help you. We are always with you with 24/7 support service.',
    'contact.info': 'Contact Information',
    'contact.writeToUs': 'Write to Us',
    'contact.sendMessage': 'Send Message',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.address': 'Address',
    'contact.workHours': 'Working Hours',
    'contact.support247': '24/7 Support',
    'contact.whyHitLoyal': 'Why HitLoyal?',
    'contact.fastResponse': 'Fast response time (within 24 hours)',
    'contact.professionalConsult': 'Professional consultation service',
    'contact.personalizedSolutions': 'Personalized solutions',
    'contact.transparentPricing': 'Transparent pricing',
    'contact.formDesc': 'Send your question and we will contact you soon.',
    'contact.fullName': 'Full Name',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.namePlaceholder': 'Enter your name',
    'contact.emailPlaceholder': 'email@example.com',
    'contact.subjectPlaceholder': 'Subject of your message',
    'contact.messagePlaceholder': 'Write your message here...',
    'contact.findOffice': 'Find Our Office',
    'contact.officeLocation': 'We are located in Baku city, Cəfər Cabbarlı street 44, Caspian Plaza building. We are close to metro stations and in an accessible location.',
    'contact.addressFull': 'Cəfər Cabbarlı 44 (Caspian Plaza)',
    'contact.city': 'Baku, Azerbaijan',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.loginTitle': 'Account Login',
    'auth.loginDesc': 'Login to your account by entering your email and password',
    'auth.signupTitle': 'New Account',
    'auth.signupDesc': 'Enter your information to create a new account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'Full Name (minimum 3 characters)',
    'auth.emailPlaceholder': 'example@example.com',
    'auth.loginButton': 'Login',
    'auth.signupButton': 'Sign Up',
    'auth.forgotPassword': 'Forgot password',
    'auth.emailAvailable': 'This email address is available',
    'auth.emailTaken': 'This email address is already in use',
    'auth.emailCheckError': 'Error occurred while checking email',
    'auth.nameRequirement': 'Name must be at least 3 characters',
    'auth.nameValid': 'Name requirements are met',
    'auth.formError': 'Form Error',
    'auth.formErrorMessage': 'Please meet all requirements',
    'auth.signupError': 'Sign Up Error',
    'auth.weakPassword': 'Weak Password',
    'auth.weakPasswordMessage': 'Please choose a stronger password (at least 3/5 points)',
    'auth.generalError': 'Error',
    'auth.signupGeneralError': 'Error occurred during sign up',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<string>('az'); // Default to Azerbaijani
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    // Check URL for language parameter
    const pathParts = location.pathname.split('/');
    const langFromUrl = pathParts[1];
    
    if (langFromUrl === 'az' || langFromUrl === 'tr' || langFromUrl === 'en') {
      setLanguage(langFromUrl);
      localStorage.setItem('language', langFromUrl);
    } else {
      // Use Azerbaijani as default instead of checking localStorage
      const defaultLanguage = 'az';
      setLanguage(defaultLanguage);
      localStorage.setItem('language', defaultLanguage);
      
      // Redirect to language-specific URL with Azerbaijani as default
      const newPath = `/${defaultLanguage}${location.pathname}${location.search}`;
      navigate(newPath, { replace: true });
    }
  }, [location.pathname, navigate]);

  const handleSetLanguage = (lang: string) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    
    // Update URL with new language
    const pathParts = location.pathname.split('/');
    if (pathParts[1] === 'az' || pathParts[1] === 'tr' || pathParts[1] === 'en') {
      pathParts[1] = lang;
    } else {
      pathParts.splice(1, 0, lang);
    }
    const newPath = pathParts.join('/') + location.search;
    navigate(newPath, { replace: true });
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage: handleSetLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
