import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'az' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  az: {
    'nav.home': 'Ana Səhifə',
    'nav.about': 'Haqqımızda',
    'nav.services': 'Xidmətlər',
    'nav.blog': 'Bloq',
    'nav.contact': 'Əlaqə',
    'nav.order': 'Sifariş Et',
    'nav.dashboard': 'İdarə Paneli',
    'nav.account': 'Hesab',
    'nav.logout': 'Çıxış',
    'nav.login': 'Giriş',
    'hero.title': 'Sosial Media Xidmətlərində Lider',
    'hero.subtitle': 'HitLoyal ilə sosial media hesablarınızı gücləndin və rəqabətdə öndə olun',
    'hero.cta': 'İndi Başla',
    'hero.learnMore': 'Daha Ətraflı',
    'hero.viewServices': 'Xidmətlərə Bax',
    'stats.services': 'Xidmət',
    'stats.clients': 'Müştəri',
    'stats.orders': 'Sifariş',
    'stats.satisfaction': 'Məmnunluq',
    'stats.completedOrders': 'Tamamlanmış Sifariş',
    'stats.happyCustomers': 'Məmnun Müştəri',
    'stats.customerSatisfaction': 'Müştəri Məmnuniyyəti',
    'stats.support247': '24/7 Dəstək',
    'features.title': 'Niyə HitLoyal?',
    'features.subtitle': 'Bizim xidmətlərimizdən istifadə etməyinizin səbəbləri',
    'features.whyUs': 'Niyə Biz?',
    'features.quality.title': 'Yüksək Keyfiyyət',
    'features.quality.description': 'Bütün xidmətlərimiz ən yüksək keyfiyyət standartlarına uyğundur',
    'features.fast.title': 'Sürətli Çatdırılma',
    'features.fast.description': 'Sifarişləriniz ən qısa müddətdə tamamlanır',
    'features.support.title': '24/7 Dəstək',
    'features.support.description': 'Hər zaman yanınızdayıq və yardıma hazırıq',
    'features.secure.title': 'Təhlükəsiz Ödəniş',
    'features.secure.description': 'Ödənişləriniz SSL şifrələməsi ilə qorunur',
    'features.guarantee.title': 'Zəmanət',
    'features.guarantee.description': 'Xidmətlərimizə 30 gün zəmanət veririk',
    'features.affordable.title': 'Münasib Qiymət',
    'features.affordable.description': 'Bazardakı ən yaxşı qiymətləri təklif edirik',
    'features.fastQuality': 'Sürətli və Keyfiyyətli',
    'features.fastQualityDesc': 'Yüksək keyfiyyətdə və sürətli xidmət təklif edirik',
    'features.support247': '24/7 Dəstək',
    'features.support247Desc': 'Hər zaman əlçatan müştəri dəstəyi xidməti',
    'features.securePayment': 'Təhlükəsiz Ödəniş',
    'features.securePaymentDesc': 'Bütün ödənişlər SSL şifrələməsi ilə qorunur',
    'features.guaranteeDesc': 'Xidmətlərimizə tam zəmanət veririk',
    'services.title': 'Xidmətlərimiz',
    'services.subtitle': 'Sosial media hesablarınız üçün geniş xidmət çeşidi',
    'services.viewAll': 'Hamısını Gör',
    'guarantees.title': 'Zəmanətlərimiz',
    'guarantees.subtitle': 'Müştəri məmnuniyyəti bizim əsas prioritetimizdir',
    'guarantees.moneyBack': 'Pul Geri Qaytarılması',
    'guarantees.moneyBackDesc': 'Əgər nəticədən razı qalmasanız, pulunuzu geri qaytarırıq',
    'guarantees.noPasswordNeeded': 'Parol Tələb Edilmir',
    'guarantees.noPasswordNeededDesc': 'Xidmətlərimiz üçün hesab parolunuza ehtiyac yoxdur',
    'guarantees.fastDelivery': 'Sürətli Çatdırılma',
    'guarantees.fastDeliveryDesc': 'Sifarişləriniz vaxtında və sürətlə yerinə yetirilir',
    'guarantees.ssl': 'SSL Şifrələmə',
    'guarantees.sslDesc': 'Bütün məlumatlarınız təhlükəsiz şəkildə qorunur',
    'guarantees.resultGuarantee': 'Nəticə Zəmanəti',
    'guarantees.satisfactionGuarantee': 'Məmnuniyyət Zəmanəti',
    'guarantees.support247': '24/7 Dəstək',
    'footer.company': 'Şirkət',
    'footer.about': 'Haqqımızda',
    'footer.contact': 'Əlaqə',
    'footer.careers': 'Karyera',
    'footer.services': 'Xidmətlər',
    'footer.instagram': 'Instagram',
    'footer.facebook': 'Facebook',
    'footer.youtube': 'YouTube',
    'footer.tiktok': 'TikTok',
    'footer.support': 'Dəstək',
    'footer.faq': 'FAQ',
    'footer.terms': 'İstifadə Şərtləri',
    'footer.privacy': 'Gizlilik Siyasəti',
    'footer.rights': 'Bütün hüquqlar qorunur.',
    'footer.description': 'Sosial media hesablarınızı gücləndirsə üçün etibarlı və keyfiyyətli xidmətlər təklif edirik.',
    'footer.whyUs': 'Niyə Biz?',
    'footer.secureReliable': 'Təhlükəsiz və Etibarlı',
    'footer.fastService': 'Sürətli Xidmət',
    'footer.support247': '24/7 Dəstək',
    'footer.copyright': '© 2024 HitLoyal. Bütün hüquqlar qorunur.',
    'footer.trustedPlatform': 'Etibarlı SMM Platforması',
    'order.title': 'Sifariş Et',
    'order.description': 'İstədiyiniz xidməti seçin və sifarişinizi verin',
    'order.selectService': 'Xidmət Seçin',
    'order.selectServicePlaceholder': 'Xidmət axtarın...',
    'order.noServices': 'Xidmət tapılmadı',
    'order.enterLink': 'Link Daxil Edin',
    'order.linkPlaceholder': 'Instagram, Facebook və ya digər link...',
    'order.quantity': 'Miqdar',
    'order.quantityPlaceholder': 'Miqdar daxil edin',
    'order.totalPrice': 'Ümumi Qiymət',
    'order.placeOrder': 'Sifarişi Ver',
    'order.minQuantity': 'Minimum miqdar',
    'order.maxQuantity': 'Maksimum miqdar',
    'order.pricePerUnit': 'Vahid qiyməti',
    'order.processing': 'Sifarişiniz emal edilir...',
    'order.selectCategory': 'Kateqoriya Seçin',
    'order.allCategories': 'Bütün Kateqoriyalar',
    'order.instagram': 'Instagram',
    'order.facebook': 'Facebook',
    'order.youtube': 'YouTube',
    'order.tiktok': 'TikTok',
    'order.twitter': 'Twitter',
    'order.telegram': 'Telegram',
    'order.linkedin': 'LinkedIn',
    'order.other': 'Digər',
    'contact.title': 'Bizimlə Əlaqə',
    'contact.description': 'Suallarınız var? Bizə yazın və ən qısa müddətdə cavab verək',
    'contact.info': 'Əlaqə Məlumatları',
    'contact.email': 'Email',
    'contact.phone': 'Telefon',
    'contact.address': 'Ünvan',
    'contact.workHours': 'İş saatları',
    'contact.support247': '24/7 Dəstək',
    'contact.addressFull': 'Bakı, Azərbaycan',
    'contact.city': 'Bakı, Azərbaycan',
    'contact.whyHitLoyal': 'Niyə HitLoyal?',
    'contact.fastResponse': 'Sürətli cavab',
    'contact.professionalConsult': 'Peşəkar məsləhət',
    'contact.personalizedSolutions': 'Fərdi həllər',
    'contact.transparentPricing': 'Şəffaf qiymət',
    'contact.writeToUs': 'Bizə yazın',
    'contact.formDesc': 'Formu doldurun və biz sizinlə əlaqə saxlayaq',
    'contact.fullName': 'Ad Soyad',
    'contact.namePlaceholder': 'Adınızı daxil edin',
    'contact.emailPlaceholder': 'Email ünvanınızı daxil edin',
    'contact.subject': 'Mövzu',
    'contact.subjectPlaceholder': 'Mesajın mövzusu',
    'contact.message': 'Mesaj',
    'contact.messagePlaceholder': 'Mesajınızı yazın',
    'contact.sendMessage': 'Mesaj Göndər',
    'contact.sending': 'Göndərilir...',
    'contact.messageSent': 'Mesajınız göndərildi! Tezliklə sizinlə əlaqə saxlayacağıq.',
    'contact.messageError': 'Mesaj göndərilərkən xəta baş verdi. Zəhmət olmasa yenidən cəhd edin.',
    'contact.findOffice': 'Ofisimizi tapın',
    'contact.officeLocation': 'Bakı şəhərindəki ofisimizə xoş gəlmisiniz',
    'blog.title': 'Bloq',
    'blog.description': 'Sosial media və rəqəmsal marketinq haqqında ən son məqalələr',
    'blog.readMore': 'Daha çox oxu',
    'blog.minuteRead': 'dəq oxu',
    'blog.backToBlog': 'Bloqa qayıt',
    'blog.relatedPosts': 'Oxşar məqalələr',
    'blog.noPosts': 'Hələ heç bir məqalə yoxdur',
    'blog.loading': 'Məqalələr yüklənir...',
    'blog.error': 'Məqalələri yükləyərkən xəta baş verdi',
    'blog.notFound': 'Məqalə tapılmadı',
    'blog.notFoundDesc': 'Axtardığınız məqalə mövcud deyil və ya silinib',
    // About page translations
    'about.title': 'Haqqımızda',
    'about.description': 'HitLoyal - sosial media böyümə və inkişafı üçün etibarlı tərəfdaşınız',
    'about.security': 'Təhlükəsizlik',
    'about.securityDesc': 'Məlumatlarınızın təhlükəsizliyi bizim prioritetimizdir',
    'about.fastService': 'Sürətli Xidmət',
    'about.fastServiceDesc': 'Sifarişləriniz ən qısa müddətdə tamamlanır',
    'about.professionalTeam': 'Peşəkar Komanda',
    'about.professionalTeamDesc': 'Təcrübəli mütəxəssislərdən ibarət komandamız',
    'about.targeted': 'Hədəfli Yanaşma',
    'about.targetedDesc': 'Hər müştəriyə fərdi yanaşma tətbiq edirik',
    'about.quality': 'Keyfiyyət',
    'about.qualityDesc': 'Yalnız yüksək keyfiyyətli xidmətlər təklif edirik',
    'about.globalReach': 'Qlobal Əhatə',
    'about.globalReachDesc': 'Dünya miqyasında xidmət göstəririk',
    'about.happyCustomers': 'Məmnun Müştəri',
    'about.completedOrders': 'Tamamlanmış Sifariş',
    'about.successRate': 'Uğur Nisbəti',
    'about.supportService': 'Dəstək Xidməti',
    'about.ourMission': 'Missiyamız',
    'about.missionText': 'Sosial media hesablarınızın böyüməsini təmin etmək və rəqəmsal dünyada uğurlu olmağınıza kömək etmək missiyamızdır.',
    'about.whyChooseUs': 'Niyə Bizi Seçməlisiniz?',
    'about.companyInfo': 'Şirkət Haqqında',
    'about.companyDescription': 'HitLoyal 2020-ci ildən bəri sosial media marketinq sahəsində fəaliyyət göstərir və minlərlə müştəriyə xidmət göstərib.',
    'about.companyServices': 'Instagram, Facebook, YouTube, TikTok və digər platformalar üçün geniş xidmət spektri təklif edirik.',
    // Admin Contact Messages translations
    'admin.contactMessages': 'Əlaqə Mesajları',
    'admin.newMessage': 'Yeni Mesaj',
    'admin.readMessage': 'Oxunub',
    'admin.repliedMessage': 'Cavablanıb',
    'admin.markAsRead': 'Oxunmuş kimi işarələ',
    'admin.markAsReplied': 'Cavablanmış kimi işarələ',
    'admin.deleteMessage': 'Mesajı sil',
    'admin.confirmDelete': 'Mesajı silmək istədiyinizdən əminsiniz?',
    'admin.messageDeleted': 'Mesaj silindi',
    'admin.messageUpdated': 'Mesaj yeniləndi',
    'admin.deleteError': 'Mesaj silinərkən xəta baş verdi',
    'admin.updateError': 'Mesaj yenilənərkən xəta baş verdi',
    'admin.loadingError': 'Mesajları yükləyərkən xəta baş verdi',
    'admin.noMessages': 'Heç bir mesaj yoxdur',
    'admin.name': 'Ad',
    'admin.email': 'Email',
    'admin.subject': 'Mövzu',
    'admin.message': 'Mesaj',
    'admin.status': 'Status',
    'admin.date': 'Tarix',
    'admin.actions': 'Əməliyyatlar',
    'common.new': 'Yeni',
    'common.read': 'Oxunub',
    'common.replied': 'Cavablanıb'
  },
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımızda',
    'nav.services': 'Hizmetler',
    'nav.blog': 'Blog',
    'nav.contact': 'İletişim',
    'nav.order': 'Sipariş Ver',
    'nav.dashboard': 'Kontrol Paneli',
    'nav.account': 'Hesap',
    'nav.logout': 'Çıkış',
    'nav.login': 'Giriş',
    'hero.title': 'Sosyal Medya Hizmetlerinde Lider',
    'hero.subtitle': 'HitLoyal ile sosyal medya hesaplarınızı güçlendirin ve rekabette öne geçin',
    'hero.cta': 'Hemen Başla',
    'hero.learnMore': 'Daha Fazla',
    'hero.viewServices': 'Hizmetleri Gör',
    'stats.services': 'Hizmet',
    'stats.clients': 'Müşteri',
    'stats.orders': 'Sipariş',
    'stats.satisfaction': 'Memnuniyet',
    'stats.completedOrders': 'Tamamlanan Sipariş',
    'stats.happyCustomers': 'Mutlu Müşteri',
    'stats.customerSatisfaction': 'Müşteri Memnuniyeti',
    'stats.support247': '7/24 Destek',
    'features.title': 'Neden HitLoyal?',
    'features.subtitle': 'Hizmetlerimizi kullanma nedenleriniz',
    'features.whyUs': 'Neden Biz?',
    'features.quality.title': 'Yüksek Kalite',
    'features.quality.description': 'Tüm hizmetlerimiz en yüksek kalite standartlarına uygundur',
    'features.fast.title': 'Hızlı Teslimat',
    'features.fast.description': 'Siparişleriniz en kısa sürede tamamlanır',
    'features.support.title': '7/24 Destek',
    'features.support.description': 'Her zaman yanınızdayız ve yardıma hazırız',
    'features.secure.title': 'Güvenli Ödeme',
    'features.secure.description': 'Ödemeleriniz SSL şifrelemesi ile korunur',
    'features.guarantee.title': 'Garanti',
    'features.guarantee.description': 'Hizmetlerimize 30 gün garanti veriyoruz',
    'features.affordable.title': 'Uygun Fiyat',
    'features.affordable.description': 'Pazardaki en iyi fiyatları sunuyoruz',
    'features.fastQuality': 'Hızlı ve Kaliteli',
    'features.fastQualityDesc': 'Yüksek kalitede ve hızlı hizmet sunuyoruz',
    'features.support247': '7/24 Destek',
    'features.support247Desc': 'Her zaman erişilebilir müşteri destek hizmeti',
    'features.securePayment': 'Güvenli Ödeme',
    'features.securePaymentDesc': 'Tüm ödemeler SSL şifrelemesi ile korunur',
    'features.guaranteeDesc': 'Hizmetlerimize tam garanti veriyoruz',
    'services.title': 'Hizmetlerimiz',
    'services.subtitle': 'Sosyal medya hesaplarınız için geniş hizmet yelpazesi',
    'services.viewAll': 'Tümünü Gör',
    'guarantees.title': 'Garantilerimiz',
    'guarantees.subtitle': 'Müşteri memnuniyeti temel önceliğimizdir',
    'guarantees.moneyBack': 'Para İade Garantisi',
    'guarantees.moneyBackDesc': 'Sonuçtan memnun kalmazsanız, paranızı iade ediyoruz',
    'guarantees.noPasswordNeeded': 'Şifre Gerekmiyor',
    'guarantees.noPasswordNeededDesc': 'Hizmetlerimiz için hesap şifrenize ihtiyaç yoktur',
    'guarantees.fastDelivery': 'Hızlı Teslimat',
    'guarantees.fastDeliveryDesc': 'Siparişleriniz zamanında ve hızlıca yerine getirilir',
    'guarantees.ssl': 'SSL Şifreleme',
    'guarantees.sslDesc': 'Tüm bilgileriniz güvenli şekilde korunur',
    'guarantees.resultGuarantee': 'Sonuç Garantisi',
    'guarantees.satisfactionGuarantee': 'Memnuniyet Garantisi',
    'guarantees.support247': '7/24 Destek',
    'footer.company': 'Şirket',
    'footer.about': 'Hakkımızda',
    'footer.contact': 'İletişim',
    'footer.careers': 'Kariyer',
    'footer.services': 'Hizmetler',
    'footer.instagram': 'Instagram',
    'footer.facebook': 'Facebook',
    'footer.youtube': 'YouTube',
    'footer.tiktok': 'TikTok',
    'footer.support': 'Destek',
    'footer.faq': 'SSS',
    'footer.terms': 'Kullanım Şartları',
    'footer.privacy': 'Gizlilik Politikası',
    'footer.rights': 'Tüm hakları saklıdır.',
    'footer.description': 'Sosyal medya hesaplarınızı güçlendirmek için güvenilir ve kaliteli hizmetler sunuyoruz.',
    'footer.whyUs': 'Neden Biz?',
    'footer.secureReliable': 'Güvenli ve Güvenilir',
    'footer.fastService': 'Hızlı Hizmet',
    'footer.support247': '7/24 Destek',
    'footer.copyright': '© 2024 HitLoyal. Tüm hakları saklıdır.',
    'footer.trustedPlatform': 'Güvenilir SMM Platforması',
    'order.title': 'Sipariş Ver',
    'order.description': 'İstediğiniz hizmeti seçin ve siparişinizi verin',
    'order.selectService': 'Hizmet Seçin',
    'order.selectServicePlaceholder': 'Hizmet ara...',
    'order.noServices': 'Hizmet bulunamadı',
    'order.enterLink': 'Link Girin',
    'order.linkPlaceholder': 'Instagram, Facebook veya diğer link...',
    'order.quantity': 'Miktar',
    'order.quantityPlaceholder': 'Miktar girin',
    'order.totalPrice': 'Toplam Fiyat',
    'order.placeOrder': 'Siparişi Ver',
    'order.minQuantity': 'Minimum miktar',
    'order.maxQuantity': 'Maksimum miktar',
    'order.pricePerUnit': 'Birim fiyatı',
    'order.processing': 'Siparişiniz işleniyor...',
    'order.selectCategory': 'Kategori Seçin',
    'order.allCategories': 'Tüm Kategoriler',
    'order.instagram': 'Instagram',
    'order.facebook': 'Facebook',
    'order.youtube': 'YouTube',
    'order.tiktok': 'TikTok',
    'order.twitter': 'Twitter',
    'order.telegram': 'Telegram',
    'order.linkedin': 'LinkedIn',
    'order.other': 'Diğer',
    'contact.title': 'Bizimle İletişime Geçin',
    'contact.description': 'Sorularınız mı var? Bize yazın ve en kısa sürede yanıt verelim',
    'contact.info': 'İletişim Bilgileri',
    'contact.email': 'E-posta',
    'contact.phone': 'Telefon',
    'contact.address': 'Adres',
    'contact.workHours': 'Çalışma saatleri',
    'contact.support247': '7/24 Destek',
    'contact.addressFull': 'Bakü, Azerbaycan',
    'contact.city': 'Bakü, Azerbaycan',
    'contact.whyHitLoyal': 'Neden HitLoyal?',
    'contact.fastResponse': 'Hızlı yanıt',
    'contact.professionalConsult': 'Profesyonel danışmanlık',
    'contact.personalizedSolutions': 'Kişiselleştirilmiş çözümler',
    'contact.transparentPricing': 'Şeffaf fiyatlandırma',
    'contact.writeToUs': 'Bize yazın',
    'contact.formDesc': 'Formu doldurun ve sizinle iletişime geçelim',
    'contact.fullName': 'Ad Soyad',
    'contact.namePlaceholder': 'Adınızı girin',
    'contact.emailPlaceholder': 'E-posta adresinizi girin',
    'contact.subject': 'Konu',
    'contact.subjectPlaceholder': 'Mesajın konusu',
    'contact.message': 'Mesaj',
    'contact.messagePlaceholder': 'Mesajınızı yazın',
    'contact.sendMessage': 'Mesaj Gönder',
    'contact.sending': 'Gönderiliyor...',
    'contact.messageSent': 'Mesajınız gönderildi! Kısa sürede sizinle iletişime geçeceğiz.',
    'contact.messageError': 'Mesaj gönderilirken hata oluştu. Lütfen tekrar deneyin.',
    'contact.findOffice': 'Ofisimizi bulun',
    'contact.officeLocation': 'Bakü şehrindeki ofisimize hoş geldiniz',
    'blog.title': 'Blog',
    'blog.description': 'Sosyal medya ve dijital pazarlama hakkında en son makaleler',
    'blog.readMore': 'Devamını oku',
    'blog.minuteRead': 'dk okuma',
    'blog.backToBlog': 'Bloga dön',
    'blog.relatedPosts': 'Benzer makaleler',
    'blog.noPosts': 'Henüz hiç makale yok',
    'blog.loading': 'Makaleler yükleniyor...',
    'blog.error': 'Makaleleri yüklerken hata oluştu',
    'blog.notFound': 'Makale bulunamadı',
    'blog.notFoundDesc': 'Aradığınız makale mevcut değil veya silinmiş',
    // About page translations
    'about.title': 'Hakkımızda',
    'about.description': 'HitLoyal - sosyal medya büyüme ve gelişimi için güvenilir ortağınız',
    'about.security': 'Güvenlik',
    'about.securityDesc': 'Verilerinizin güvenliği önceliğimizdir',
    'about.fastService': 'Hızlı Hizmet',
    'about.fastServiceDesc': 'Siparişleriniz en kısa sürede tamamlanır',
    'about.professionalTeam': 'Profesyonel Ekip',
    'about.professionalTeamDesc': 'Deneyimli uzmanlardan oluşan ekibimiz',
    'about.targeted': 'Hedefli Yaklaşım',
    'about.targetedDesc': 'Her müşteriye özel yaklaşım uygularız',
    'about.quality': 'Kalite',
    'about.qualityDesc': 'Sadece yüksek kaliteli hizmetler sunuyoruz',
    'about.globalReach': 'Küresel Kapsam',
    'about.globalReachDesc': 'Dünya çapında hizmet veriyoruz',
    'about.happyCustomers': 'Mutlu Müşteri',
    'about.completedOrders': 'Tamamlanan Sipariş',
    'about.successRate': 'Başarı Oranı',
    'about.supportService': 'Destek Hizmeti',
    'about.ourMission': 'Misyonumuz',
    'about.missionText': 'Sosyal medya hesaplarınızın büyümesini sağlamak ve dijital dünyada başarılı olmanıza yardım etmek misyonumuzdur.',
    'about.whyChooseUs': 'Neden Bizi Seçmelisiniz?',
    'about.companyInfo': 'Şirket Hakkında',
    'about.companyDescription': 'HitLoyal 2020 yılından beri sosyal medya pazarlama alanında faaliyet göstermekte ve binlerce müşteriye hizmet vermiştir.',
    'about.companyServices': 'Instagram, Facebook, YouTube, TikTok ve diğer platformlar için geniş hizmet yelpazesi sunuyoruz.',
    // Admin Contact Messages translations
    'admin.contactMessages': 'İletişim Mesajları',
    'admin.newMessage': 'Yeni Mesaj',
    'admin.readMessage': 'Okundu',
    'admin.repliedMessage': 'Yanıtlandı',
    'admin.markAsRead': 'Okundu olarak işaretle',
    'admin.markAsReplied': 'Yanıtlandı olarak işaretle',
    'admin.deleteMessage': 'Mesajı sil',
    'admin.confirmDelete': 'Mesajı silmek istediğinizden emin misiniz?',
    'admin.messageDeleted': 'Mesaj silindi',
    'admin.messageUpdated': 'Mesaj güncellendi',
    'admin.deleteError': 'Mesaj silinirken hata oluştu',
    'admin.updateError': 'Mesaj güncellenirken hata oluştu',
    'admin.loadingError': 'Mesajlar yüklenirken hata oluştu',
    'admin.noMessages': 'Hiç mesaj yok',
    'admin.name': 'Ad',
    'admin.email': 'E-posta',
    'admin.subject': 'Konu',
    'admin.message': 'Mesaj',
    'admin.status': 'Durum',
    'admin.date': 'Tarih',
    'admin.actions': 'İşlemler',
    'common.new': 'Yeni',
    'common.read': 'Okundu',
    'common.replied': 'Yanıtlandı'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'az';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
