// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnsragearbdkxpbhhyez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxuc3JhZ2VhcmJka3hwYmhoeWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzgyNDEsImV4cCI6MjA2NzE1NDI0MX0.fP2P2ZJursJ6yI44WPVjznOzTJw-yTVFFhCQEVsjEps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});